// Generated by scripts/build-header-assets.ts — do not edit.
/** Pixel size of hero-handwriting-mask.webp, for the headline box's aspect ratio. */
export const HERO_MASK_SIZE = { width: 1280, height: 402 } as const;
